version: '2'
plugins:
  tslint:
    enabled: true
    config: tslint.json
  nodesecurity:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
exclude_paths:
  - '.github/'
  - 'projects/**/*.spec.ts'
  - 'projects/ng-generic-pipe/karma.conf.js'
  - 'projects/ng-generic-pipe-demo/'
ratings:
  paths:
    - 'projects/ng-generic-pipe/**/**.ts'